name: 'Terragrunt summirize Action for GitHub'

description: 'Finds all terragrunt plan files in the project repository and adds comment to PR'

on:
  workflow_call:
    inputs:
      plan_file_name:
        description: 'The name of the plan file'
        required: false
        type: string
        default: 'plan.json'
      runs_on:
        description: 'the list of runners'
        required: true
        type: list
        default: []


jobs:
  reusable_workflow_job:
    runs-on: ${{ inputs.runs_on }}
    steps:
    - run: |
        echo '| CHANGE |                     RESOURCE                      |' > summary.md ;\
        echo '|--------|---------------------------------------------------|' >> summary.md

    - name: Find plan files
      run: |
        docker run -v $PWD:/workspace -w /workspace 
        ghcr.io/dineshba/tf-summarize /bin/sh -c \
        "find . -name ${{ inputs.plan_file_name }} -exec tf-summarize -md {} \; |grep -v ' CHANGE ' |grep -v '\-\-\-\-' >> summary.md" ;\
        echo "MESSAGE=$(cat summary.md)" >> $GITHUB_ENV

    - uses: mshick/add-pr-comment@v2
      with:
        message: $MESSAGE